In [1]:
import swat

#### Start CAS session

In [2]:
server = "rdcgrd133"
port = 16271
s = swat.CAS(server, port)

In [3]:
tbl_name = 'hmeq'
target = 'bad'
tbl = s.upload('U:\\data\\hmeq.csv', casout=dict(name=tbl_name, replace=True))

NOTE: Executing action 'table.loadTable'.
NOTE: Cloud Analytic Services made the uploaded file available as table HMEQ in caslib CASUSER(bigebr).
NOTE: Action 'table.loadTable' used (Total process time):
NOTE:       real time               0.031258 seconds
NOTE:       cpu time                0.109983 seconds (351.86%)
NOTE:       total nodes             1 (32 cores)
NOTE:       total memory            252.23G
NOTE:       memory                  66.74M (0.03%)
NOTE: The table HMEQ has been created in caslib CASUSER(bigebr) from binary data uploaded to Cloud Analytic Services.
NOTE: Action 'table.upload' used (Total process time):
NOTE:       real time               0.064262 seconds
NOTE:       cpu time                0.114983 seconds (178.93%)
NOTE:       total nodes             1 (32 cores)
NOTE:       total memory            252.23G
NOTE:       memory                  66.74M (0.03%)

In [4]:
s.fetch(table=tbl_name, to=5)

NOTE: Executing action 'table.fetch'.
NOTE: Action 'table.fetch' used (Total process time):
NOTE:       real time               0.005226 seconds
NOTE:       cpu time                0.005000 seconds (95.68%)
NOTE:       total nodes             1 (32 cores)
NOTE:       total memory            252.23G
NOTE:       memory                  2.09M (0.00%)

,BAD,LOAN,MORTDUE,VALUE,REASON,JOB,YOJ,DEROG,DELINQ,CLAGE,NINQ,CLNO,DEBTINC
0,1.0,1100.0,25860.0,39025.0,HomeImp,Other,10.5,0.0,0.0,94.366667,1.0,9.0,NaN
1,1.0,1300.0,70053.0,68400.0,HomeImp,Other,7.0,0.0,2.0,121.833333,0.0,14.0,NaN
2,1.0,1500.0,13500.0,16700.0,HomeImp,Other,4.0,0.0,0.0,149.466667,1.0,10.0,NaN
3,1.0,1500.0,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,1700.0,97800.0,112000.0,HomeImp,Office,3.0,0.0,0.0,93.333333,0.0,14.0,NaN

In [5]:
s.loadactionset(actionset='dataSciencePilot')

NOTE: Executing action 'builtins.loadActionSet'.
NOTE: Added action set 'dataSciencePilot'.
NOTE: Action 'builtins.loadActionSet' used (Total process time):
NOTE:       real time               0.005928 seconds
NOTE:       cpu time                0.002999 seconds (50.59%)
NOTE:       total nodes             1 (32 cores)
NOTE:       total memory            252.23G
NOTE:       memory                  228.16K (0.00%)

[actionset]

 'dataSciencePilot'

+ Elapsed: 0.00593s, user: 0.002s, sys: 0.001s, mem: 0.223mb

In [6]:
s.highcardinality(table=tbl_name)

NOTE: Executing action 'dataPreprocess.highCardinality'.
NOTE: Action 'dataPreprocess.highCardinality' used (Total process time):
NOTE:       real time               0.012857 seconds
NOTE:       cpu time                0.032996 seconds (256.64%)
NOTE:       total nodes             1 (32 cores)
NOTE:       total memory            252.23G
NOTE:       memory                  7.23M (0.00%)

[HighCardinalityDetails]

 Cardinality Estimates for HMEQ

    Variable       N   NMiss  CardinalityEstimate  CardinalityRatio
 0       BAD  5960.0     0.0                  2.0          0.000336
 1      LOAN  5960.0     0.0                542.0          0.090940
 2   MORTDUE  5442.0   518.0               5005.0          0.919699
 3     VALUE  5848.0   112.0               5520.0          0.943912
 4    REASON  5708.0   252.0                  2.0          0.000350
 5       JOB  5681.0   279.0                  6.0          0.001056
 6       YOJ  5445.0   515.0                101.0          0.018549
 7     DEROG  5252.0   708.0                 11.0          0.002094
 8    DELINQ  5380.0   580.0                 14.0          0.002602
 9     CLAGE  5652.0   308.0               5393.0          0.954176
 10     NINQ  5450.0   510.0                 16.0          0.002936
 11     CLNO  5738.0   222.0                 63.0          0.010979
 12  DEBTINC  4693.0  1267.0               4598.0          0.979757

+ Elapsed: 0.0129s, user: 0.027s, sys: 0.006s, mem: 7.23mb

In [7]:
res = s.dataSciencePilot.dsAutoml(table=tbl_name, 
                                  target=target, 
                                  # use all inputs ...or specify ...inputs=[....]
                                  inputs = ['loan', 'job', 'reason', 'clno', 'ninq'],
                                  modelTypes = ['decisionTree'],
                                  # an example of manual override of the role auto-detection
                                  # the below means use cnlno and ninq as intervals while for the rest of inputs,
                                  # do auto-detection
                                  explorationPolicy = dict(nominal=dict(intervals=['clno', 'ninq'])),
                                  sampleSize = 1,
                                  featuresOut = dict(name='fout', replace=True),
                                  transformationOut = dict(name='tout', replace=True),
                                  pipelinesOut = dict(name='pout', replace=True),
                                  saveState = dict(name='fmout', replace=True))

NOTE: Executing action 'dataSciencePilot.dsAutoMl'.
NOTE: Added action set 'autotune'.
NOTE: Executing action 'autotune.tuneDecisionTree'.
NOTE: Executing action 'builtins.loadActionSet'.
NOTE: Added action set 'decisionTree'.
NOTE: Action 'builtins.loadActionSet' used (Total process time):
NOTE:       real time               0.002335 seconds
NOTE:       cpu time                0.001999 seconds (85.61%)
NOTE:       total nodes             1 (32 cores)
NOTE:       total memory            252.23G
NOTE:       memory                  244.44K (0.00%)
NOTE: Executing action 'decisionTree.dtreeTrain'.
NOTE: Action 'decisionTree.dtreeTrain' used (Total process time):
NOTE:       real time               0.253781 seconds
NOTE:       cpu time                1.870716 seconds (737.14%)
NOTE:       total nodes             1 (32 cores)
NOTE:       total memory            252.23G
NOTE:       memory                  80.28M (0.03%)
NOTE: Executing action 'decisionTree.dtreeScore'.
NOTE: Action 'decisionTree.dtreeScore' used (Total process time):
NOTE:       real time               0.025525 seconds
NOTE:       cpu time                0.066990 seconds (262.45%)
NOTE:       total nodes             1 (32 cores)
NOTE:       total memory            252.23G
NOTE:       memory                  70.82M (0.03%)
NOTE: Executing action 'percentile.assess'.
NOTE: Action 'percentile.assess' used (Total process time):
NOTE:       real time               0.021216 seconds
NOTE:       cpu time                0.083987 seconds (395.87%)
NOTE:       total nodes             1 (32 cores)
NOTE:       total memory            252.23G
NOTE:       memory                  11.13M (0.00%)
NOTE: Action 'autotune.tuneDecisionTree' used (Total process time):
NOTE:       real time               10.011754 seconds
NOTE:       cpu time                0.466929 seconds (4.66%)
NOTE:       total nodes             1 (32 cores)
NOTE:       total memory            252.23G
NOTE:       memory                  6.88M (0.00%)
NOTE: Action 'dataSciencePilot.dsAutoMl' used (Total process time):
NOTE:       real time               10.934958 seconds
NOTE:       cpu time                2.188667 seconds (20.02%)
NOTE:       total nodes             1 (32 cores)
NOTE:       total memory            252.23G
NOTE:       memory                  1.14M (0.00%)

In [8]:
res['OutputCasTables']

,casLib,Name,Rows,Columns,casTable
0,CASUSER(bigebr),pout,1,17,"CASTable('pout', caslib='CASUSER(bigebr)')"
1,CASUSER(bigebr),tout,7,21,"CASTable('tout', caslib='CASUSER(bigebr)')"
2,CASUSER(bigebr),fout,9,9,"CASTable('fout', caslib='CASUSER(bigebr)')"
3,CASUSER(bigebr),fmout,1,2,"CASTable('fmout', caslib='CASUSER(bigebr)')"

In [9]:
s.fetch(table='fout')['Fetch']

NOTE: Executing action 'table.fetch'.
NOTE: Action 'table.fetch' used (Total process time):
NOTE:       real time               0.004180 seconds
NOTE:       cpu time                0.002999 seconds (71.75%)
NOTE:       total nodes             1 (32 cores)
NOTE:       total memory            252.23G
NOTE:       memory                  1.98M (0.00%)

,FeatureId,Name,IsNominal,FTGPipelineId,NInputs,InputVar1,InputVar2,InputVar3,Label
0,1.0,cpy_int_med_imp_CLNO,0.0,6.0,1.0,CLNO,,,CLNO: Low Missing Rate - Median Imputation
1,2.0,cpy_int_med_imp_NINQ,0.0,6.0,1.0,NINQ,,,NINQ: Low Missing Rate - Median Imputation
2,3.0,miss_ind_NINQ,1.0,1.0,1.0,NINQ,,,NINQ: Significant Missing - Missing indicator
3,4.0,hc_cnt_LOAN,0.0,4.0,1.0,LOAN,,,LOAN: High Cardinality - count encoding
4,5.0,hc_cnt_log_LOAN,0.0,5.0,1.0,LOAN,,,LOAN: High Cardinality - log(count) encoding
5,6.0,hc_lbl_cnt_LOAN,0.0,3.0,1.0,LOAN,,,LOAN: High Cardinality - label count encoding
6,7.0,hc_tar_frq_rat_LOAN,0.0,2.0,1.0,LOAN,,,LOAN: High Cardinality - target frequency rati...
7,8.0,cpy_nom_miss_lev_lab_JOB,1.0,7.0,1.0,JOB,,,JOB: Low Missing Rate - Missing Level
8,9.0,cpy_nom_miss_lev_lab_REASON,1.0,7.0,1.0,REASON,,,REASON: Low Missing Rate - Missing Level

In [10]:
s.fetch(table='pout')['Fetch']

NOTE: Executing action 'table.fetch'.
NOTE: Action 'table.fetch' used (Total process time):
NOTE:       real time               0.003622 seconds
NOTE:       cpu time                0.003000 seconds (82.83%)
NOTE:       total nodes             1 (32 cores)
NOTE:       total memory            252.23G
NOTE:       memory                  1.98M (0.00%)

,PipelineId,ModelType,MLType,Objective,ObjectiveType,Target,NFeatures,Feat1Id,Feat1IsNom,Feat2Id,Feat2IsNom,Feat3Id,Feat3IsNom,Feat4Id,Feat4IsNom,Feat5Id,Feat5IsNom
0,1.0,binary classification,dtree,0.170582,MCE,BAD,5.0,6.0,0.0,2.0,0.0,8.0,1.0,1.0,0.0,9.0,1.0

In [11]:
features_df = s.fetch(table='fout')['Fetch']
pipeline_df = s.fetch(table='pout')['Fetch']

NOTE: Executing action 'table.fetch'.
NOTE: Action 'table.fetch' used (Total process time):
NOTE:       real time               0.003995 seconds
NOTE:       cpu time                0.003999 seconds (100.10%)
NOTE:       total nodes             1 (32 cores)
NOTE:       total memory            252.23G
NOTE:       memory                  1.98M (0.00%)
NOTE: Executing action 'table.fetch'.
NOTE: Action 'table.fetch' used (Total process time):
NOTE:       real time               0.003768 seconds
NOTE:       cpu time                0.002999 seconds (79.59%)
NOTE:       total nodes             1 (32 cores)
NOTE:       total memory            252.23G
NOTE:       memory                  1.98M (0.00%)

In [12]:
# reconstruct the first pipeline:- basically extract the features and nominals.
def extrac_pipeline_meta_data(pipeline_df, features_df, pipeline_id):
    row = pipeline_df[pipeline_df.PipelineId == pipeline_id]
    n_feats = int(row['NFeatures'][0])
    features = []
    nominals = []
    for i in range(1, n_feats+1):
        col_name = 'Feat{}Id'.format(i)
        feat_id = row[col_name][0]
        col_name = 'Feat{}IsNom'.format(i)
        is_nom = row[col_name][0]
        feat_name = features_df[features_df.FeatureId == feat_id]['Name'][feat_id - 1]
        features.append(feat_name)
        if is_nom:
            nominals.append(feat_name)
    return features, nominals

In [13]:
# do astore scoring of your datasets...
s.loadactionset(actionset='astore')

NOTE: Executing action 'builtins.loadActionSet'.
NOTE: Added action set 'astore'.
NOTE: Action 'builtins.loadActionSet' used (Total process time):
NOTE:       real time               0.000404 seconds
NOTE:       cpu time                0.001000 seconds (247.52%)
NOTE:       total nodes             1 (32 cores)
NOTE:       total memory            252.23G
NOTE:       memory                  209.81K (0.00%)

[actionset]

 'astore'

+ Elapsed: 0.000404s, user: 0.001s, mem: 0.205mb

In [14]:
featurized_tbl = 'featurized_tbl'
s.astore.score(table=tbl_name, copyvars=[target], rstore='fmout',
               casout=dict(name=featurized_tbl, replace=True))

NOTE: Executing action 'astore.score'.
NOTE: Action 'astore.score' used (Total process time):
NOTE:       real time               0.022919 seconds
NOTE:       cpu time                0.101985 seconds (444.98%)
NOTE:       total nodes             1 (32 cores)
NOTE:       total memory            252.23G
NOTE:       memory                  38.90M (0.02%)

[OutputCasTables]

             casLib            Name  Rows  Columns  \
 0  CASUSER(bigebr)  featurized_tbl  5960       10

                                             casTable
 0  CASTable('featurized_tbl', caslib='CASUSER(big...

[Timing]

 Task Timing

                  Task   Seconds   Percent
 0   Loading the Store  0.000110  0.005612
 1  Creating the State  0.011347  0.578148
 2             Scoring  0.007787  0.396766
 3               Total  0.019626  1.000000

+ Elapsed: 0.0229s, user: 0.077s, sys: 0.025s, mem: 38.9mb

In [15]:
s.fetch(table=featurized_tbl, to=5)

NOTE: Executing action 'table.fetch'.
NOTE: Action 'table.fetch' used (Total process time):
NOTE:       real time               0.002836 seconds
NOTE:       cpu time                0.002000 seconds (70.52%)
NOTE:       total nodes             1 (32 cores)
NOTE:       total memory            252.23G
NOTE:       memory                  2.02M (0.00%)

,cpy_int_med_imp_CLNO,cpy_int_med_imp_NINQ,miss_ind_NINQ,hc_cnt_LOAN,hc_cnt_log_LOAN,hc_lbl_cnt_LOAN,hc_tar_frq_rat_LOAN,cpy_nom_miss_lev_lab_JOB,cpy_nom_miss_lev_lab_REASON,BAD
0,9.0,1.0,1.0,1.0,0.000000,528.0,0.5,3.0,2.0,1.0
1,14.0,0.0,1.0,1.0,0.000000,461.0,0.5,3.0,2.0,1.0
2,10.0,1.0,1.0,2.0,0.693147,385.0,0.5,3.0,2.0,1.0
3,20.0,1.0,0.0,2.0,0.693147,385.0,0.5,0.0,0.0,1.0
4,14.0,0.0,1.0,2.0,0.693147,359.0,0.5,2.0,2.0,0.0

In [16]:
s.loadactionset(actionset='autotune')

NOTE: Executing action 'builtins.loadActionSet'.
NOTE: Added action set 'autotune'.
NOTE: Action 'builtins.loadActionSet' used (Total process time):
NOTE:       real time               0.000416 seconds
NOTE:       cpu time                0.000000 seconds (0.00%)
NOTE:       total nodes             1 (32 cores)
NOTE:       total memory            252.23G
NOTE:       memory                  232.53K (0.00%)

[actionset]

 'autotune'

+ Elapsed: 0.000416s, mem: 0.227mb

In [17]:
pipeline_id = 1
pp_features, pp_nom_features = extrac_pipeline_meta_data(pipeline_df, features_df, pipeline_id)

In [18]:
pp_features

['hc_lbl_cnt_LOAN',
 'cpy_int_med_imp_NINQ',
 'cpy_nom_miss_lev_lab_JOB',
 'cpy_int_med_imp_CLNO',
 'cpy_nom_miss_lev_lab_REASON']

In [19]:
pp_nom_features

['cpy_nom_miss_lev_lab_JOB', 'cpy_nom_miss_lev_lab_REASON']

In [20]:
s.autotune.tunedecisiontree(trainoptions=dict(table=featurized_tbl,
                                              target=target,
                                              inputs=pp_features,
                                              nominals=pp_nom_features),
                            tunerOptions=dict(seed=123))

NOTE: Executing action 'autotune.tuneDecisionTree'.
NOTE: Autotune is started for 'Decision Tree' model.
NOTE: Autotune option SEARCHMETHOD='GA'.
NOTE: Autotune option MAXTIME=36000 (sec.).
NOTE: Autotune option SEED=123.
NOTE: Autotune objective is 'Mean Square Error'.
NOTE: Autotune number of parallel evaluations is set to 4, each using 0 worker nodes.
NOTE: Executing action 'builtins.loadActionSet'.
NOTE: Added action set 'decisionTree'.
NOTE: Action 'builtins.loadActionSet' used (Total process time):
NOTE:       real time               0.002392 seconds
NOTE:       cpu time                0.001999 seconds (83.57%)
NOTE:       total nodes             1 (32 cores)
NOTE:       total memory            252.23G
NOTE:       memory                  228.47K (0.00%)
         Iteration       Evals     Best Objective  Elapsed Time
                 0           1             0.1526          0.36
                 1          17             0.1408          2.32
                 2          29             0.1402          4.08
                 3          39             0.1402          5.59
                 4          49             0.1402          6.80
                 5          59             0.1391          8.17
NOTE: Data was partitioned during tuning, to tune based on validation score; the final model is trained and scored on all data.
NOTE: Executing action 'decisionTree.dtreeTrain'.
NOTE: Action 'decisionTree.dtreeTrain' used (Total process time):
NOTE:       real time               0.345457 seconds
NOTE:       cpu time                2.951551 seconds (854.39%)
NOTE:       total nodes             1 (32 cores)
NOTE:       total memory            252.23G
NOTE:       memory                  105.96M (0.04%)
NOTE: Executing action 'decisionTree.dtreeScore'.
NOTE: Action 'decisionTree.dtreeScore' used (Total process time):
NOTE:       real time               0.022321 seconds
NOTE:       cpu time                0.041994 seconds (188.14%)
NOTE:       total nodes             1 (32 cores)
NOTE:       total memory            252.23G
NOTE:       memory                  4.74M (0.00%)
NOTE: Autotune time is 8.64 seconds.
NOTE: Action 'autotune.tuneDecisionTree' used (Total process time):
NOTE:       real time               8.663522 seconds
NOTE:       cpu time                0.382941 seconds (4.42%)
NOTE:       total nodes             1 (32 cores)
NOTE:       total memory            252.23G
NOTE:       memory                  283.47K (0.00%)

[ModelInfo]

 Decision Tree for FEATURIZED_TBL_AUTOTUNE_20SEP2019:16:53:01

                                 Descr        Value
 0                Number of Tree Nodes   529.000000
 1              Max Number of Branches     2.000000
 2                    Number of Levels    13.000000
 3                    Number of Leaves   265.000000
 4                      Number of Bins   200.000000
 5              Minimum Size of Leaves     5.000000
 6              Maximum Size of Leaves  1054.000000
 7                 Number of Variables     5.000000
 8   Alpha for Cost-Complexity Pruning     0.000000
 9         Number of Observations Used  5960.000000
 10              Maximum STD of Leaves     0.500000
 11              Minimum STD of Leaves     0.173993
 12                 Mean Squared Error     0.096710

[ScoreInfo]

                          Descr                             Value
 0  Number of Observations Read                              5960
 1  Number of Observations Used                              5960
 2           Mean Squared Error                      0.0967095378

[TunerInfo]

 Tuner Information

                            Parameter              Value
 0                         Model Type      Decision Tree
 1           Tuner Objective Function  Mean Square Error
 2                      Search Method                 GA
 3                    Population Size                 10
 4                 Maximum Iterations                  5
 5     Maximum Tuning Time in Seconds              36000
 6                    Validation Type   Single Partition
 7      Validation Partition Fraction               0.30
 8                          Log Level                  2
 9                               Seed                123
 10    Number of Parallel Evaluations                  4
 11  Number of Workers per Subsession                  0

[TunerResults]

 Tuner Results

     Evaluation  MAXLEVEL  NBINS      CRIT  MeanSqErr  EvaluationTime
 0            0        11     20  VARIANCE   0.152584        0.357058
 1           57        13    200  VARIANCE   0.139100        0.565533
 2           54        12    200  VARIANCE   0.139420        0.540479
 3           55        12    165  VARIANCE   0.139481        0.486048
 4           27        11    200  VARIANCE   0.140162        0.410945
 5           32        13    199     FTEST   0.140233        0.539635
 6           14        11    200     FTEST   0.140774        0.448797
 7           41        13    161     FTEST   0.141302        0.535345
 8           18        13    166     FTEST   0.141305        0.463821
 9            4        10    200     FTEST   0.141332        0.848198
 10          46        10    165     FTEST   0.141332        0.345687

[IterationHistory]

 Tuner Iteration History

    Iteration  Evaluations  Best_obj  Time_sec
 0          0            1  0.152584  0.357058
 1          1           17  0.140774  2.681371
 2          2           29  0.140162  4.436963
 3          3           39  0.140162  5.947481
 4          4           49  0.140162  7.154323
 5          5           59  0.139100  8.525547

[EvaluationHistory]

 Tuner Evaluation History

     Evaluation  Iteration  MAXLEVEL  NBINS      CRIT  MeanSqErr  \
 0            0          0        11     20  VARIANCE   0.152584
 1            1          1         2     60  VARIANCE   0.159861
 2            2          1        12     80  VARIANCE   0.144528
 3            3          1        14     40     CHAID   0.156651
 4            4          1        10    200     FTEST   0.141332
 5            5          1         6    180     CHAID   0.165798
 6            6          1        18     20     CHAID   0.156190
 7            7          1         4    100     FTEST   0.154327
 8            8          1        20    140  VARIANCE   0.158319
 9            9          1         8    160     FTEST   0.144173
 10          10          1        11     20  VARIANCE   0.152584
 11          11          1        11    110     FTEST   0.145968
 12          12          1        20    110     FTEST   0.158464
 13          13          1         2    110     FTEST   0.160343
 14          14          1        11    200     FTEST   0.140774
 15          15          1        11     20     FTEST   0.152584
 16          16          1        11    110     CHAID   0.159681
 17          17          1        11    110  VARIANCE   0.145355
 18          18          2        13    166     FTEST   0.141305
 19          19          2         7    152     FTEST   0.147983
 20          20          2        11     96     CHAID   0.159536
 21          21          2        13     56     FTEST   0.153395
 22          22          2        13    130  VARIANCE   0.148469
 23          23          2        12     70  VARIANCE   0.149905
 24          24          2         7    196  VARIANCE   0.146201
 25          25          2        11    153     FTEST   0.145771
 26          26          2        11    200     CHAID   0.162467
 27          27          2        11    200  VARIANCE   0.140162
 28          28          2        20    200     FTEST   0.151808
 29          29          2         2    200     FTEST   0.160343
 30          30          3        13    199     CHAID   0.163966
 31          31          3        11    140     FTEST   0.143584
 32          32          3        13    199     FTEST   0.140233
 33          33          3         9    198  VARIANCE   0.142465
 34          34          3        13    153     FTEST   0.141751
 35          35          3         9    152     FTEST   0.144218
 36          36          3        10    130  VARIANCE   0.141342
 37          37          3        12    149  VARIANCE   0.143760
 38          38          3        20    200  VARIANCE   0.151196
 39          39          3         2    200  VARIANCE   0.160343
 40          40          4        11    169  VARIANCE   0.145271
 41          41          4        13    161     FTEST   0.141302
 42          42          4        10    184  VARIANCE   0.143545
 43          43          4        11    154  VARIANCE   0.146746
 44          44          4        10    139  VARIANCE   0.142617
 45          45          4        10    140     CHAID   0.162053
 46          46          4        10    165     FTEST   0.141332
 47          47          4        16    200  VARIANCE   0.146748
 48          48          4        11    155  VARIANCE   0.145900
 49          49          4         7    200  VARIANCE   0.146047
 50          50          5        14    154     FTEST   0.143799
 51          51          5        11    193     FTEST   0.145295
 52          52          5        12    155  VARIANCE   0.143813
 53          53          5        11    184  VARIANCE   0.143285
 54          54          5        12    200  VARIANCE   0.139420
 55          55          5        12    165  VARIANCE   0.139481
 56          56          5        11    198  VARIANCE   0.141753
 57          57          5        13    200  VARIANCE   0.139100
 58          58          5         9    200  VARIANCE   0.142232
 59          59          5        11    178  VARIANCE   0.145042

     EvaluationTime
 0         0.357058
 1         0.472069
 2         0.476791
 3         0.877615
 4         0.848198
 5         0.662278
 6         0.349685
 7         0.150920
 8         0.598876
 9         0.330251
 10        0.000000
 11        0.417363
 12        0.603182
 13        0.194905
 14        0.448797
 15        0.301375
 16        0.518562
 17        0.262035
 18        0.463821
 19        0.321976
 20        0.462103
 21        0.304149
 22        0.397668
 23        0.294114
 24        0.320506
 25        0.345307
 26        1.137904
 27        0.410945
 28        0.631652
 29        0.243779
 30        1.470887
 31        0.479760
 32        0.539635
 33        0.487529
 34        0.428753
 35        0.350278
 36        0.346844
 37        0.385541
 38        0.623456
 39        0.228912
 40        0.508119
 41        0.535345
 42        0.487033
 43        0.435626
 44        0.285314
 45        0.696147
 46        0.345687
 47        0.661444
 48        0.460103
 49        0.351185
 50        0.557331
 51        0.529302
 52        0.521153
 53        0.522589
 54        0.540479
 55        0.486048
 56        0.546653
 57        0.565533
 58        0.315648
 59        0.308991

[BestConfiguration]

 Best Configuration

              Parameter        Name         Value
 0           Evaluation  Evaluation            57
 1  Maximum Tree Levels    MAXLEVEL            13
 2         Maximum Bins       NBINS           200
 3            Criterion        CRIT      VARIANCE
 4    Mean Square Error   Objective  0.1390995154

[TunerSummary]

 Tuner Summary

                                           Parameter      Value
 0             Initial Configuration Objective Value   0.152584
 1                Best Configuration Objective Value   0.139100
 2               Worst Configuration Objective Value   0.165798
 3  Initial Configuration Evaluation Time in Seconds   0.357058
 4     Best Configuration Evaluation Time in Seconds   0.565522
 5                 Number of Improved Configurations   7.000000
 6                Number of Evaluated Configurations  59.000000
 7                      Total Tuning Time in Seconds   8.635176
 8                           Parallel Tuning Speedup   3.201115

[TunerTiming]

 Tuner Task Timing

                           Task   Time_sec  Time_percent
 0               Model Training  25.562074     92.474840
 1                Model Scoring   1.499222      5.423673
 2  Total Objective Evaluations  27.069140     97.926890
 3                        Tuner   0.573053      2.073110
 4               Total CPU Time  27.642193    100.000000

[HyperparameterImportance]

 Hyperparameter Importance

   Hyperparameter  RelImportance
 0           CRIT       1.000000
 1       MAXLEVEL       0.938781
 2          NBINS       0.603443

+ Elapsed: 8.66s, user: 0.302s, sys: 0.081s, mem: 0.277mb

In [21]:
s.close()